PREFIX was: <https://was-course.interactions.ics.unisg.ch/farm-ontology#>

SELECT ?requiredMoistureLevel WHERE {
GRAPH <https://sandbox-graphdb.interactions.ics.unisg.ch/was-exercise-3-tibor#> {
   bind (<https://sandbox-graphdb.interactions.ics.unisg.ch/was-exercise-3-tibor#crop-604a27a0-d7fb-4826-b0f8-f9b0c6046001> as ?crop)
        ?crop a was:Crop.
        ?crop was:requiredMoistureLevel ?requiredMoistureLevel.
 }
}